export { PaginaContacto } from './contacto'
export { PaginaNosotros } from './nosotros'
export { PaginaProyectos } from './proyectos'
export { PaginaServicios } from './servicios'
export { PaginaServiciosReels } from './servicios-reels'
export { PaginaServiciosModelos } from './servicios-modelos'
export { PaginaServiciosFotoProducto } from './servicios-fotoproducto'