export { PaginaContacto } from './contacto'
export { PaginaNosotros } from './nosotros'
export { PaginaProyectos } from './proyectos'
export { PaginaServicios } from './servicios'
export { PaginaCart } from './cartPage'